FROM redis:7-alpine

COPY ./redis/sentinel/redis.sentinel1.conf /usr/local/etc/redis/redis.sentinel1.conf
COPY ./redis/sentinel/redis.sentinel2.conf /usr/local/etc/redis/redis.sentinel2.conf
COPY ./redis/sentinel/redis.sentinel3.conf /usr/local/etc/redis/redis.sentinel3.conf