receivers:
  # Receive traces via OTLP from instrumented services (keep for traces)
  otlp:
    protocols:
      grpc:
      http:

  # Receive logs via Fluent Forward (Fluentd/Fluent Bit)
  fluentforward:
    endpoint: 0.0.0.0:24224

processors:
  filter/drop_non_json:
    logs:
      log_record:
        - 'IsString(body) and not IsMatch(body, "^[\\{]")'

  transform/parse_json_body:
    error_mode: ignore
    log_statements:
      - context: log
        conditions:
          - body != nil and Substring(body, 0, 2) == "{\""
        statements:
          - set(cache, ParseJSON(body))
          - flatten(cache, "")
          - merge_maps(attributes, cache, "upsert")
#          - set(time, Time(attributes["Timestamp"], "%Y-%m-%dT%H:%M:%S%j"))
          - set(severity_text, "TRACE") where attributes["Level"] == "Trace"
          - set(severity_number, 1) where attributes["Level"] == "Trace"
          - set(severity_text, "DEBUG") where attributes["Level"] == "Debug"
          - set(severity_number, 5) where attributes["Level"] == "Debug"

          - set(severity_text, "INFO") where attributes["Level"] == "Information"
          - set(severity_number, 9) where attributes["Level"] == "Information"

          - set(severity_text, "WARN") where attributes["Level"] == "Warning"
          - set(severity_number, 13) where attributes["Level"] == "Warning"

          - set(severity_text, "ERROR") where attributes["Level"] == "Error"
          - set(severity_number, 17) where attributes["Level"] == "Error"

          - set(severity_text, "FATAL") where attributes["Level"] == "Fatal"
          - set(severity_number, 21) where attributes["Level"] == "Fatal"

  filter/include_app_channel:
    logs:
      log_record:
        - attributes["channel"] != "app"


exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    logs_index: "otel-logs"
    traces_index: "otel-traces"

  debug:
    verbosity: normal

service:
  telemetry:
    logs:
      level: info
  pipelines:
    logs:
      receivers: [fluentforward]
      processors: [filter/drop_non_json, transform/parse_json_body, filter/include_app_channel]
      exporters: [elasticsearch, debug]
    traces:
      receivers: [otlp]
      exporters: [elasticsearch]
